version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backstage
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432